"""
Campus pathfinding for the cart bridge simulator.

Uses the pre-baked campus graph (generated by the mobile app's
generate-campus-graph.ts script) for instant A* routing.
Falls back to straight-line if the graph file is missing.
"""

import heapq
import json
import math
import os
from typing import Optional

# Path to the pre-baked graph (shared with the mobile app)
_GRAPH_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "app",
    "constants",
    "campus-graph.json",
)

UCF_CENTER_LAT = 28.6024
UCF_CENTER_LON = -81.2001
MAX_CAMPUS_DISTANCE_M = 2000.0

_node_map: dict[str, tuple[float, float]] = {}
_adjacency: dict[str, list[str]] = {}
_loaded = False


def _haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def _load_graph() -> bool:
    global _loaded
    if _loaded:
        return bool(_node_map)

    _loaded = True
    if not os.path.exists(_GRAPH_PATH):
        print(f"[PATH] Campus graph not found at {_GRAPH_PATH}")
        print("[PATH] Run: cd packages/app && npx tsx scripts/generate-campus-graph.ts")
        return False

    with open(_GRAPH_PATH) as f:
        data = json.load(f)

    for n in data["nodes"]:
        _node_map[n["id"]] = (n["lat"], n["lon"])
        _adjacency[n["id"]] = []

    for a, b in data["edges"]:
        _adjacency[a].append(b)
        _adjacency[b].append(a)

    print(f"[PATH] Loaded campus graph: {len(_node_map)} nodes, {len(data['edges'])} edges")
    return True


def _find_nearest(lat: float, lon: float) -> Optional[str]:
    best_id = None
    best_dist = float("inf")
    for nid, (nlat, nlon) in _node_map.items():
        d = _haversine_m(lat, lon, nlat, nlon)
        if d < best_dist:
            best_dist = d
            best_id = nid
    return best_id


def _astar(start_id: str, goal_id: str) -> list[str]:
    goal_lat, goal_lon = _node_map[goal_id]

    # Priority queue: (f_score, node_id)
    open_set: list[tuple[float, str]] = []
    heapq.heappush(open_set, (0.0, start_id))

    g_scores: dict[str, float] = {start_id: 0.0}
    parents: dict[str, Optional[str]] = {start_id: None}
    closed: set[str] = set()

    while open_set:
        _, current = heapq.heappop(open_set)
        if current == goal_id:
            path = []
            node: Optional[str] = goal_id
            while node is not None:
                path.append(node)
                node = parents.get(node)
            path.reverse()
            return path

        if current in closed:
            continue
        closed.add(current)

        clat, clon = _node_map[current]

        for neighbor in _adjacency.get(current, []):
            if neighbor in closed:
                continue
            nlat, nlon = _node_map[neighbor]
            tent_g = g_scores[current] + _haversine_m(clat, clon, nlat, nlon)
            if tent_g < g_scores.get(neighbor, float("inf")):
                g_scores[neighbor] = tent_g
                h = _haversine_m(nlat, nlon, goal_lat, goal_lon)
                parents[neighbor] = current
                heapq.heappush(open_set, (tent_g + h, neighbor))

    return []  # no path found


def find_path(
    start_lat: float,
    start_lon: float,
    goal_lat: float,
    goal_lon: float,
) -> list[dict]:
    """
    Find a path between two GPS coordinates using the pre-baked campus graph.
    Returns a list of {"latitude": ..., "longitude": ...} waypoints.
    Falls back to straight line if graph unavailable or path not found.
    """
    if not _load_graph():
        return _straight_line(start_lat, start_lon, goal_lat, goal_lon)

    start_node = _find_nearest(start_lat, start_lon)
    goal_node = _find_nearest(goal_lat, goal_lon)
    if not start_node or not goal_node:
        return _straight_line(start_lat, start_lon, goal_lat, goal_lon)

    path_ids = _astar(start_node, goal_node)
    if not path_ids:
        return _straight_line(start_lat, start_lon, goal_lat, goal_lon)

    waypoints = [{"latitude": _node_map[nid][0], "longitude": _node_map[nid][1]} for nid in path_ids]

    # Prepend/append exact start/goal for precision
    first = waypoints[0]
    if first["latitude"] != start_lat or first["longitude"] != start_lon:
        waypoints.insert(0, {"latitude": start_lat, "longitude": start_lon})
    last = waypoints[-1]
    if last["latitude"] != goal_lat or last["longitude"] != goal_lon:
        waypoints.append({"latitude": goal_lat, "longitude": goal_lon})

    return waypoints


def _straight_line(lat1: float, lon1: float, lat2: float, lon2: float, n: int = 20) -> list[dict]:
    """Fallback: simple interpolated straight line."""
    return [
        {
            "latitude": lat1 + (lat2 - lat1) * i / (n - 1),
            "longitude": lon1 + (lon2 - lon1) * i / (n - 1),
        }
        for i in range(n)
    ]
